### PR TITLE
Lab based frontend

### PR DESCRIPTION
**Pull request by jtpio**
Skeleton app using JupyterLab components.

Check out the [README](https://github.com/jtpio/mamba-navigator/blob/ca860450814a8a1001117fdf6fdaec0980608901/app/README.md) for more details on the dev setup and how to add new plugins.

skeleton

### CODE REVIEW

**Comment by jtpio** [comment]
cc @hbcarlos

For now the skeleton app is placed under the `/app` folder, but we could already start moving it to the top-level if we decide to go with this approach.

We might also want to wrap the existing Vue components into Lumino widgets, by instantiating a `new Vue({ el: this.node })` object manually (if necessary).

**Comment by wolfv** [comment]
This is cool!

**Comment by jtpio** [comment]
Another interesting path to explore would be to reuse the plugins from the `jupyter_conda` extension: https://github.com/fcollonval/jupyter_conda

The plugins are defined here: https://github.com/fcollonval/jupyter_conda/blob/a7fd182a6b6a47a7ca48b545ba946e2937fcf4b1/labextension/src/index.ts#L174

But they might need to be split-up a bit more to be usable in the mamba navigator.

**Comment by SylvainCorlay** [comment]
Noice!

**Comment by wolfv** [comment]
Should we merge this PR? @jtpio or is this WIP?

**Comment by jtpio** [comment]
The skeleton is ready and lives in its own subfolder for now.

So we could merge and iterate on it, and decide whether to integrate and reuse the existing Vue components, or rewrite the logic differently.

**Comment by hbcarlos** [comment]
Nice, I'll take a look as soon as I can.

**Comment by jtpio** [comment]
> Another interesting path to explore would be to reuse the plugins from the `jupyter_conda` extension: https://github.com/fcollonval/jupyter_conda

Ha, didn't notice this open issue, nice! https://github.com/TheSnakePit/mamba-navigator/issues/8

**Pull request merged**
